In [1]:
import pandas as pd
import numpy as np
file_path = "../data/raw/sales_data.csv"
df = pd.read_csv(file_path)
print("Shape:", df.shape)
df.head()

Shape: (76000, 16)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [2]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
print(df.columns.tolist())

['date', 'store_id', 'product_id', 'category', 'region', 'inventory_level', 'units_sold', 'units_ordered', 'price', 'discount', 'weather_condition', 'promotion', 'competitor_pricing', 'seasonality', 'epidemic', 'demand']

In [3]:
df["date"] = pd.to_datetime(
    df["date"],
    errors="coerce"
)
print(df["date"].dtype)

datetime64[us]

In [4]:
print("Invalid dates:", df["date"].isna().sum())

Invalid dates: 0

In [5]:
missing = df.isnull().sum()
print(missing[missing > 0])

Series([], dtype: int64)

In [6]:
missing_percentage = (
    df.isnull().mean() * 100
).sort_values(ascending=False)
print(missing_percentage[missing_percentage > 0])

Series([], dtype: float64)

In [7]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 0

In [8]:
numeric_columns = df.select_dtypes(
    include=np.number
).columns
print(numeric_columns.tolist())

['inventory_level', 'units_sold', 'units_ordered', 'price', 'discount', 'promotion', 'competitor_pricing', 'epidemic', 'demand']

In [9]:
df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
inventory_level,76000.0,301.062842,226.510161,0.00,136.0000,227.0,408.0000,2267.00
units_sold,76000.0,88.827316,43.994525,0.00,58.0000,84.0,114.0000,426.00
units_ordered,76000.0,89.090645,162.404627,0.00,0.0000,0.0,121.0000,1616.00
price,76000.0,67.726028,39.377899,4.74,31.9975,64.5,95.8300,228.03
discount,76000.0,9.087039,7.475781,0.00,5.0000,10.0,10.0000,25.00
promotion,76000.0,0.328947,0.469834,0.00,0.0000,0.0,1.0000,1.00
competitor_pricing,76000.0,69.454029,40.943818,4.29,32.6200,65.7,97.9325,261.22
epidemic,76000.0,0.200000,0.400003,0.00,0.0000,0.0,0.0000,1.00
demand,76000.0,104.317158,46.964801,4.00,71.0000,100.0,133.0000,430.00

In [10]:
print(
    "Negative units sold:",
    (df["units_sold"] < 0).sum()
)

Negative units sold: 0

In [11]:
print(
    "Invalid prices:",
    (df["price"] <= 0).sum()
)

Invalid prices: 0

In [12]:
print(
    "Negative inventory:",
    (df["inventory_level"] < 0).sum()
)

Negative inventory: 0

In [13]:
print(
    "Negative demand:",
    (df["demand"] < 0).sum()
)

Negative demand: 0

In [14]:
print("Products:", df["product_id"].nunique())
print("Stores:", df["store_id"].nunique())
print("Categories:", df["category"].nunique())
print("Regions:", df["region"].nunique())

Products: 20
Stores: 5
Categories: 5
Regions: 4

In [15]:
print("\nCategories:")
print(df["category"].unique())

Categories:
<StringArray>
['Electronics', 'Clothing', 'Groceries', 'Toys', 'Furniture']
Length: 5, dtype: str

In [16]:
print("\nRegions:")
print(df["region"].unique())

Regions:
<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [17]:
date_counts = (
    df.groupby("date")
      .size()
)
print(date_counts.describe())

count    760.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
dtype: float64

In [18]:
print(
    "Number of unique dates:",
    df["date"].nunique()
)
print(
    "Date range:",
    df["date"].min(),
    "to",
    df["date"].max()
)

Number of unique dates: 760
Date range: 2022-01-01 00:00:00 to 2024-01-30 00:00:00

In [19]:
product_history = (
    df.groupby("product_id")["date"]
      .agg(["min", "max", "count"])
      .sort_values("count")
)
product_history.head(10)

                  min        max  count
product_id
P0001      2022-01-01 2024-01-30   3800
P0002      2022-01-01 2024-01-30   3800
P0003      2022-01-01 2024-01-30   3800
P0004      2022-01-01 2024-01-30   3800
P0005      2022-01-01 2024-01-30   3800
P0006      2022-01-01 2024-01-30   3800
P0007      2022-01-01 2024-01-30   3800
P0008      2022-01-01 2024-01-30   3800
P0009      2022-01-01 2024-01-30   3800
P0010      2022-01-01 2024-01-30   3800

In [20]:
product_history.head()

                  min        max  count
product_id
P0001      2022-01-01 2024-01-30   3800
P0002      2022-01-01 2024-01-30   3800
P0003      2022-01-01 2024-01-30   3800
P0004      2022-01-01 2024-01-30   3800
P0005      2022-01-01 2024-01-30   3800

In [21]:
product_history.tail()

                  min        max  count
product_id
P0016      2022-01-01 2024-01-30   3800
P0017      2022-01-01 2024-01-30   3800
P0018      2022-01-01 2024-01-30   3800
P0019      2022-01-01 2024-01-30   3800
P0020      2022-01-01 2024-01-30   3800

In [22]:
store_product_counts = (
    df.groupby(
        ["store_id", "product_id"]
    )
    .size()
    .reset_index(name="records")
)

store_product_counts.head()

  store_id product_id  records
0     S001      P0001      760
1     S001      P0002      760
2     S001      P0003      760
3     S001      P0004      760
4     S001      P0005      760

In [23]:
Q1 = df["units_sold"].quantile(0.25)
Q3 = df["units_sold"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[
    (df["units_sold"] < lower_bound) |
    (df["units_sold"] > upper_bound)
]
print("Number of potential sales outliers:", len(outliers))

Number of potential sales outliers: 1411

In [24]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["day_of_week"] = df["date"].dt.dayofweek
df["week_of_year"] = df["date"].dt.isocalendar().week.astype(int)
df["is_weekend"] = (
    df["day_of_week"] >= 5
).astype(int)

In [25]:
df[
    [
        "date",
        "year",
        "month",
        "day_of_week",
        "week_of_year",
        "is_weekend"
    ]
].head()

        date  year  month  day_of_week  week_of_year  is_weekend
0 2022-01-01  2022      1            5            52           1
1 2022-01-01  2022      1            5            52           1
2 2022-01-01  2022      1            5            52           1
3 2022-01-01  2022      1            5            52           1
4 2022-01-01  2022      1            5            52           1

In [26]:
df = df.sort_values(
    ["product_id", "store_id", "date"]
).reset_index(drop=True)

In [27]:
processed_path = "../data/processed/sales_data_cleaned.csv"
df.to_csv(
    processed_path,
    index=False
)
print("Cleaned dataset saved!")
print("Shape:", df.shape)

Cleaned dataset saved!
Shape: (76000, 22)

In [29]:
from pathlib import Path
output_path = Path("../data/processed/sales_data_cleaned.csv")
df.to_csv(output_path, index=False)
print("Cleaned dataset saved successfully")
print("Path:", output_path)
print("Rows:", len(df))
print("Columns:", len(df.columns))

Cleaned dataset saved successfully
Path: ..\data\processed\sales_data_cleaned.csv
Rows: 76000
Columns: 22